name: Generate Podcast Audio
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install TTS Engine
        run: pip install edge-tts

      - name: Run Audio Generator
        run: python main.py

      - name: Simpan Hasil Audio
        uses: actions/upload-artifact@v4
        with:
          name: hasil-podcast-mp3
          path: podcast_output/
          
